name: Docker Image CI

on:
  push:
    branches: [ "master", "ci" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ps2dev/ps2sdk

    steps:
    - uses: actions/checkout@v3
    - name: Get dependencies
      run: |
        apk add build-base
        
    - name: Compile MASP
      run: |
        cd contrib/masp
        chmod +x ./configure && ./configure
        make clean all -j$(getconf _NPROCESSORS_ONLN)
